### ISSUE TITLE
List with no entries does not render

### ISSUE THREAD

**Issue by craighton** [jung3o/VacStatus#83]
A created list with no entries does not render anything except the header with viewed.

**Comment by wartab** [comment]
This bug is happening here:
/public/js/pages/list.js on line 515.

I checked in my debugger and at that point the array called list is empty and you try to index the element at 0, which causes you to call .map() on undefined.

I'm not familiar with Github (I don't know how to create merge requests), but I think a simple fix would be the following at the beginning of the render method:
```javascript
        var list,
        page,
        emptyMessage,
        pagedList;

		list = this.props.list;
		page = this.props.page;
		page = page <= 1 || page > list.length ? 1 : page;

        if (list[page - 1] === undefined)
        {
            emptyMessage = (list.length === 0) ? "This list is empty." : "This list page is empty.";
            return React.createElement("tbody", null,
                React.createElement("tr", null,
                    React.createElement(
                        "td", {colSpan: "5"}, emptyMessage
                    )
                )
            );
        }
```

This is untested, but feel free to get inspiration from it =)

**Comment by jung3o** [comment]
Thank you, this has been fixed.
